// Generated by gencpp from file ipa_building_msgs/RoomExplorationActionGoal.msg
// DO NOT EDIT!


#ifndef IPA_BUILDING_MSGS_MESSAGE_ROOMEXPLORATIONACTIONGOAL_H
#define IPA_BUILDING_MSGS_MESSAGE_ROOMEXPLORATIONACTIONGOAL_H


#include <string>
#include <vector>
#include <map>
#include <memory>

// opencv的头文件
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>

#include <Eigen/Dense>

namespace ipa_building_msgs{


struct Point_x_y{
  float x;
  float y;
};

struct Point_x_y_theta{
  float x;
  float y;
  float theta;
};


struct Point_x_y_z{
  float x;
  float y;
  float z;
};

struct RoomExplorationActionGoal{
    
  double map_resolution;
  Point_x_y_z map_origin;
  double robot_radius;
  double coverage_radius;
  Point_x_y_theta starting_position;
  int planning_mode ;
  cv::Mat input_map; 
  cv::Mat input_map_after_erode;
  float min_line_cleaning_distance;
  int complementary_path_index;
  int need_hybrid_index;
  int index_to_boundary;
  double min_cell_area;
  double grid_spacing_in_meter;
  };

}


#endif // IPA_BUILDING_MSGS_MESSAGE_ROOMEXPLORATIONACTIONGOAL_H
